name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env: # Set environment variables for the entire job here.
      GO_VERSION: 1.21.1
      NDK_VERSION: r25c
      NODE_VERSION: 16
      AAR_FILE_NAME: my_custom_name.aar

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}


      - name: Install Gomobile
        run: |
          go install golang.org/x/mobile/cmd/gobind@latest
          go install golang.org/x/mobile/cmd/gomobile@latest
          #          env PATH=$PATH:~/go/bin 
          gomobile init

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: ${{ env.NDK_VERSION }}
          add-to-path: false

      - name: Gomobile build
        id: gomobile_build  # Add an id to this step, so you can refer to its outputs in later steps.
        run: |
          
          go get golang.org/x/mobile/bind
          go get -d github.com/Cyberavater/goPlay
          gomobile bind -target=android -javapkg=org.rclone -o $AAR_FILE_NAME github.com/Cyberavater/goPlay

        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          GO111MODULE: off


      # Add this step to upload the generated AAR file as an artifact.
      - name: Upload AAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-aar-file
          path: ${{ env.AAR_FILE_NAME }}  # Use the environment variable here.
