# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - name: install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gobind@latest
          go install golang.org/x/mobile/cmd/gomobile@latest
          env PATH=$PATH:~/go/bin gomobile init

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.20+101'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      #      - name: Install NDK
      #        run: sdkmanager "ndk-bundle"
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: 'r25c'

      - name: Gomobile build
        run: |
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          env PATH=$PATH:~/go/bin gomobile bind -target=android -javapkg=org.rclone ../